### ISSUE TITLE
How do you add an Espresso test to the test-only module?

### ISSUE THREAD

**Issue by bsstokes** [googlesamples/android-testing-templates#32]
I tried to add an Espresso test to `module-flavor1-androidTest-only`, but I haven't gotten very far.

I copied [`EspressoTest`](https://github.com/googlesamples/android-testing-templates/blob/master/AndroidTestingBlueprint-kotlinApp/app/src/androidTest/java/com/example/android/testing/blueprint/ui/espresso/EspressoTest.kt) into `module-flavor1-androidTest-only` and added the dependencies that it seemed to need.

My changes: https://github.com/googlesamples/android-testing-templates/compare/master...bsstokes:add-espresso-test-to-test-only-module

When I run this new test, I'm getting:

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference
at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:410)
at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at com.example.android.testing.blueprint.HelloTestingBlueprintActivity.onCreate(HelloTestingBlueprintActivity.kt:44)
at android.app.Activity.performCreate(Activity.java:6999)
at android.app.Activity.performCreate(Activity.java:6990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.testing.blueprint.flavor1/com.example.android.testing.blueprint.HelloTestingBlueprintActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v7.widget.DecorContentParent.setWindowCallback(android.view.Window$Callback)' on a null object reference
at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:410)
at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at com.example.android.testing.blueprint.HelloTestingBlueprintActivity.onCreate(HelloTestingBlueprintActivity.kt:44)
at android.app.Activity.performCreate(Activity.java:6999)
at android.app.Activity.performCreate(Activity.java:6990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
... 9 more

Test running failed: Instrumentation run failed due to 'Process crashed.'
```

Does anybody have any ideas?

It'd be awesome if somebody could add an Espresso test to `module-flavor1-androidTest-only` as an example.

**Comment by jenzz** [comment]
Unfortunately, this is not possible at the moment:
- https://issuetracker.google.com/issues/71854337
- https://issuetracker.google.com/issues/69242362
- https://issuetracker.google.com/issues/65374122

**Comment by bsstokes** [comment]
Thanks for the update. I'll keep following those issues.

**Comment by asavill** [comment]
Is this supported yet?

**Comment by MahmoudMabrok** [comment]
is there any updates @bsstokes  ?
