### ISSUE TITLE
JUnit3 tests are not working

### ISSUE THREAD

**Issue by thaussma** [googlesamples/android-testing-templates#9]
Hello,
I want to use the ``com.android.test`` plugin with JUnit3 instrumentation tests. Unfortunately this does not work because the ``ActivityInstrumentationTestCase2`` class cannot be found by dalvik when the tests are started. Am I doing something wrong? 

I forked the android-testing-templates [here](https://github.com/thaussma/android-testing-templates) and pushed the changes for JUnit3.

Logcat reports:

    Unable to resolve superclass of Lcom/example/android/testing/blueprint/test/AndroidTestOnlyModuleTest; 

This results in following output when running ``am instrument``:

    Time: 0
    There was 1 failure:
    1) com.example.android.testing.blueprint.test.AndroidTestOnlyModuleTest
    java.lang.ClassNotFoundException: com.example.android.testing.blueprint.test.AndroidTestOnlyModuleTest
    	at java.lang.Class.classForName(Native Method)
    	at java.lang.Class.forName(Class.java:204)
    	at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:94)
    	at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:115)
    	at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(    TestRequestBuilder.java:712)
    	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:661)
    	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:329)
    	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:226)
    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
    Caused by: java.lang.NoClassDefFoundError: com/example/android/testing/blueprint/test/    AndroidTestOnlyModuleTest
    	... 9 more
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.android.testing.blueprint.test.AndroidTestOnlyModuleTest" on path: DexPathList[[zip file "/data/app/com.example.android.testing.blueprint.test-2.apk", zip file "/data/app/com.example.android.testing.blueprint.flavor1-2.apk"], nativeLibraryDirectories=[/data/app-lib/com.example.android.testing.blueprint.test-2, /data/app-lib/com.example.android.testing.blueprint.flavor1-2, /system/lib]]
    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
    	... 9 more
    
    FAILURES!!!
    Tests run: 0,  Failures: 1

**Comment by slinzner** [comment]
Thanks. I can reproduce the problem locally but this is a tools issue. Can you please file a bug on the tools testing team: https://code.google.com/p/android/issues/list?q=label:Subcomponent-Tools-test-support?
